---
- name: recheche de l etat du container mariadb
  containers.podman.podman_container_info:
    name: "mariadb_{{pod_prestashop}}"
  register: 'db_info'

- name: deployement de mariadb
  containers.podman.podman_container:
    name: "mariadb_{{pod_prestashop}}"
    state: started
    pod: "{{ pod_prestashop }}"
    image: "{{ prestashop_db_image }}"
    cpus: "{{ prestashop_CPU_db }}"
    restart_policy: 'always'
    volume: "{{ pod_prestashop }}_vol_db:/var/lib/mysql"
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "{{ prestashop_dbname }}"
      MYSQL_USER: "{{ prestashop_dbuser }}"
      MYSQL_PASSWORD: "{{ prestashop_dbpassw }}"
  when: "not db_info.containers"
  

- name: recheche de l etat du container prestashop
  containers.podman.podman_container_info:
    name: "prestashop_{{pod_prestashop}}"
  register: 'db_info'

- name: deployment de prestashop
  containers.podman.podman_container:
    name: "prestashop_{{pod_prestashop}}"
    state: started
    pod: "{{ pod_prestashop }}"
    image: "{{ prestashop_web_image }}"
    cpus: "{{ prestashop_CPU_web }}"
    restart_policy: 'always'
    volume:
      - "{{ pod_prestashop }}_vol_app:/var/www/html"
    env:
      DB_SERVER: "{{ prestashop_fqdn }}"
      DB_NAME: "{{ prestashop_dbname }}"
      DB_USER: "{{ prestashop_dbuser }}"
      DB_PASSWD: "{{ prestashop_dbpassw }}"
      ADMIN_MAIL: "{{ prestashop_admin_login }}"
      ADMIN_PASSWD: "{{ prestashop_adminpasswd }}"
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: "{{ prestashop_fqdn }}"
  notify:
    - creation_systemd_pod_prestashop
    - persistance_pod_pod_prestashop
  when: "not db_info.containers"
  
  
# https://hub.docker.com/_/mariadb
# https://hub.docker.com/r/prestashop/prestashop
