---
- name: Preparation du volume de haproxy
  containers.podman.podman_volume:
    name: "haproxy_etc"
    state: present

- name: creation du volume du repertoire  var lib
  containers.podman.podman_volume:
    name: "haproxy_stats"
    state: present

- name: pour le POC copie des cles dans le volume letsencrypt
  copy:
    src: "{{ role_path }}/files/haproxy.pem"
    dest: '/var/lib/containers/storage/volumes/certbot_vol_etc_Letsencrypt/_data'


