---
- name: Creation du pod des services mails
  containers.podman.podman_pod:
    name: "{{ pod_mail }}"
    state: started
    hostname: "{{ mails_fqdn }}" 
    ports:
      - "{{ mails_port_smtp }}:25"
      - "{{ mails_port_submission }}:587"
      - "{{ mails_port_imaps }}:993"
      - "{{ mails_port_pop3s }}:995"
      - "{{ mails_port_sieve }}:4190"

- name: Creation du volume de fichers de config pour postfix
  containers.podman.podman_volume:
    name: "{{ pod_mail }}_postfix_etc_postfix"
    state: present

- name: Creation du volume du spool des mails
  containers.podman.podman_volume: 
    name: "{{ pod_mail }}_postfix_vars_pool_mail"
    state: present

- name: Creation du volume de fichiers de config pour dovecot
  containers.podman.podman_volume:
    name: "{{ pod_mail }}_dovecot_etc_dovecot"
    state: present

- name: Creation du volume pour opendkim
  containers.podman.podman_volume:
    name: "{{ pod_mail }}_vol_dkim"
    state: present

- name: Creation du volume pour mariadb
  containers.podman.podman_volume:
    name: "{{ pod_mail }}_vol_db"
    state: present

- name: Creation du volume du script de remplissage de la db
  containers.podman.podman_volume:    
    name: "{{ pod_mail }}_vol_db_boot"
    state: present 

- name: Creation du volume de stockage des mails
  containers.podman.podman_volume:
    name: "{{ pod_mail }}_vol_mails"
    state: present


- name: preparation de remplissage du volume de fichiers de configuration postfix
  template:
    src: "{{ role_path }}/templates/postfix/main.cf.j2"
    dest: "/tmp/main.cf"

- name: preparation de remplissage du volume de fichiers de configuration postfix
  template:
    src: "{{ role_path }}/templates/postfix/master.cf.j2"
    dest: "/tmp/master.cf"

- name: preparation de remplissage du volume de fichiers de configuration postfix
  template:
    src: "{{ role_path }}/templates/postfix/mysql-virtual-alias-maps.cf.j2"
    dest: "/tmp/mysql-virtual-alias-maps.cf"

- name: preparation de remplissage du volume de fichiers de configuration postfix
  template:
    src: "{{ role_path }}/templates/postfix/mysql-virtual-email2email.cf.j2"
    dest: "/tmp/mysql-virtual-email2email.cf"

- name: preparation de remplissage du volume de fichiers de configuration postfix
  template:
    src: "{{ role_path }}/templates/postfix/mysql-virtual-mailbox-maps.cf.j2"
    dest: "/tmp/mysql-virtual-mailbox-maps.cf"
      
- name: preparation de remplissage du volume de fichiers de configuration postfix
  template:
    src: "{{ role_path }}/templates/postfix/mysql-virtual-mailbox-domains.cf.j2"
    dest: "/tmp/mysql-virtual-mailbox-domains.cf"


- name: remplissage du volume de fichiers de configuration postfix
  command:
    cmd: "mv /tmp/{{ item }} /home/{{ user_rootless }}/.local/share/containers/storage/volumes/{{ pod_mail }}_postfix_etc_postfix/_data"
  loop:
    - main.cf
    - master.cf
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-email2email.cf
    - mysql-virtual-mailbox-maps.cf
    - mysql-virtual-mailbox-domains.cf



# https://www.linode.com/docs/guides/email-with-postfix-dovecot-and-mysql/
# voir pour creer dynamiquement un volume par nom de domaine ou par user ? risque de perte de visibilité ?
