---
- name: recheche de l etat du container haproxy
  containers.podman.podman_container_info:
    name: "haproxy_{{haproxy_uid}}"
  register: 'db_info'

- name: copie du fichier de configuration en temporaire
  template:
    src: "/{{ role_path }}/templates/haproxy.j2"
    dest: '/tmp/haproxy.cfg'
  when: "not db_info.containers"

- name: copie du fichier dans le volume
  command:
    cmd: "mv /tmp/haproxy.cfg /var/lib/containers/storage/volumes/haproxy_etc/_data"
  when: "not db_info.containers"

- name: haproxy en RootFull
  containers.podman.podman_container:
    name: "haproxy_{{haproxy_uid}}"
    state: started
    image: "{{ haproxy_image }}"
    cpus: "{{ haproxy_CPU }}"
    restart_policy: 'always'
    publish:
      - "25:25"
      - "80:80"
      - "443:443"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    volume:
      - 'haproxy_etc:/usr/local/etc/haproxy/'
      - 'haproxy_stats:/var/lib/haproxy/'
      - 'certbot_vol_etc_Letsencrypt:/etc/certs'
  notify:
    - creation_systemd_haproxy
    - persistance_haproxy
  when: "not db_info.containers"
