---
- name: haproxy en RootFull
  containers.podman.podman_container:
    name: haproxy_{{haproxy_uid}}
    state: started
    image: "{{ haproxy_image }}"
    cpus: "{{ haproxy_CPU }}"
    publish:
      - "25:25"
      - "80:80"
      - "443:443"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    volume:
      - 'haproxy_etc:/usr/local/etc/haproxy/'
      - 'haproxy_stats:/var/lib/haproxy/'
      - 'certbot_vol_etc_Letsencrypt:/etc/certs'
  notify:
    - creation_systemd_haproxy
    - persistance_haproxy
