---
- name: creation_systemd_haproxy
  command:
    chdir: '/etc/systemd/system/'
    cmd: "podman generate systemd --files --name haproxy_{{haproxy_uid}}" 
 
- name: persistance_haproxy
  systemd:
    enabled: true
    #state: 'started'
    name: "{{ item }}"
    daemon-reload: true
  loop:
    - "container-haproxy_{{haproxy_uid}}.service"

