---
- name: Installation de crund pour Podman
  yum:
    name: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/runc-1.0.0-149.rc93.el7.x86_64.rpm
    state: present
  when: ansible_distribution == "Amazon"

- name: Installation de Podman
#  package:
#    name: podman
#    state: latest
  command: 'yum install podman -y'
  when: ansible_distribution == "Amazon" 


- name: Installation de Podman
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - crun
    - podman
  when: ansible_distribution == "CentOS"


- name: Installation de Podman
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - runc
    - podman
  vars:
    tests:
      - '"ansible_distribution" == "Ubuntu"'
      - '"ansible_distribution_version" is version("20.09", ">")'
  when: tests is all

- name: reboot du serveur pour application du CGROUP V2
  reboot:

- name: wait serveur reboot
  wait_for:
    port: '22'
    delay: '20'

#crun va serir pour utiliser podman en rootless sur centos stream 8
