---
- name: creation_systemd_pod_wordpress
  command:
    chdir: '~/.config/systemd/user/'
    cmd: "podman generate systemd --files --name {{ pod_wordpress }}"

- name: persistance_pod_pod_wordpress
  systemd:
    scope: 'user'
    enabled: true
    name: "{{ item }}"
    daemon-reload: true
  loop:
    - "pod-{{ pod_wordpress }}.service"
    - "container-mariadb_{{ pod_wordpress }}.service"
    - "container-wordpress_{{ pod_wordpress }}.service"

# handlers for wordpress
