---
- name: creation_systemd_pod_ELK
  command:
    chdir: '~/.config/systemd/user/'
    cmd: "podman generate systemd --files --name {{ pod_ELK }}"

- name: persistance_pod_pod_ELK
  systemd:
    scope: 'user'
    enabled: true
    name: "{{ item }}"
    daemon-reload: true
  loop:
    - "pod-{{ pod_ELK }}.service"
    - "container-elastic-search_{{ pod_ELK }}.service"
    - "container-kibana_{{ pod_ELK }}.service"

