---
- name: Creation des volumes pour les fichiers de zones et de configuration DNS
  containers.podman.podman_volume:
    name: "{{ item }}"
  loop:
    - Bind9_etc
    - Bind9_var_cache_lib
    - Bind9_var_lib_bin
    - Bind9_var_log


- name: Integration des fichiers de configuration de base de bind9
  template:
    src: "/{{ role_path }}/templates/bind/named.conf"
    dest: "/home/{{ user_rootless }}/.local/share/containers/storage/volumes/Bind9_etc/_data/named.conf"
    owner: root
    group: '106'
    mode: '644'

- name: Integration des fichiers de configuration de zone bind9
  template:
    src: "/{{ role_path }}/templates/bind/db.exemple.local"
    dest: "/home/{{ user_rootless }}/.local/share/containers/storage/volumes/Bind9_var_lib_bin/_data/db.exemple.local"
    owner: root
    group: '106'
    mode: '660'

- name: Integration des fichiers de configuration de zone inverse bind9                                   
  template:            
    src: "/{{ role_path }}/templates/bind/db.exemple.local.reverse"
    dest: "/home/{{ user_rootless }}/.local/share/containers/storage/volumes/Bind9_var_lib_bin/_data/db.exemple.local.reverse"
    owner: root                                                              
    group: '106'                                                             
    mode: '660'   


- name: Creation du fichier de logs bind9
  file:
    path: "/home/{{ user_rootless }}/.local/share/containers/storage/volumes/Bind9_var_log/_data/querylog"
    state: touch
    owner: 'root'
    group: '106'
    mode: '660'

