---
#- name: opendkim_gen_key
#  containers.podman.podman_container:
#    name: opendkimPod{{ pod_mail }}
#    command: "opendkim-genkey --directory=/etc/opendkim --subdomains --domain={{ mails_fqdn }} --selector=default"

- name: creation_systemd_{{ pod_mail }}
  command:
    chdir: '~/.config/systemd/user/'
    cmd: "podman generate systemd --files --name {{ pod_mail }}"

- name: persistance-pod_{{ pod_mail }}
  systemd:
    scope: 'user'
    enabled: true
    name: "{{ item }}"
    daemon-reload: true
  loop:
    - "pod-{{ pod_mail }}.service"
    - "container-mariadb_{{ pod_mail }}.service"
    - "container-opendkim_{{ pod_mail }}.service"
    - "container-dovecot_{{ pod_mail }}.service"
    - "container-postfix_{{ pod_mail }}.service"

# handlers file for PodMail
